services:
  - type: web
    name: roomrent
    env: python
    region: oregon
    rootDir: .
    buildCommand: pip install -r rent-app/requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:kabeer33room@db.juwmyppqlpmividjcfss.supabase.co:5432/postgres?sslmode=require
      - key: ROOM_NAME
        value: Room 33
      - key: RENDER
        value: true
      - key: ADMIN_PASSWORD_HASH
        value: "REPLACE_WITH_HASH_FROM_LOCAL_MACHINE"

    healthCheckPath: /
